---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

inputs:
  - name: pcf-pipelines
  - name: pivnet-product

params:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  PRODUCT_NAME:
  SINGLETON_JOB_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  ROOT_SERVICE_ACCOUNT_JSON:
  DB_HOST:
  DB_USERNAME:
  DB_PASSWORD:
  DB_PORT:
  CA_CERT:
  CLIENT_CERT:
  CLIENT_KEY:

run:
  path: pcf-pipelines/tasks/config-tiles/config-gcp-service-broker/task.sh
