---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

inputs:
  - name: pcf-pipelines
  - name: pivnet-product

params:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  PRODUCT_NAME:
  SINGLETON_JOB_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  SERVICES_NETWORK:
  REDIS_MAX_MEMORY:
  REDIS_BROKER_SERVICE_INSTANCE_LIMIT:
  ON_DEMAND_SERVICE_INSTANCE_LIMIT:
  VM_EXTENSIONS:
  SMALL_PLAN_SELECTOR:
  SMALL_PLAN_NAME:
  SMALL_PLAN_DESCRIPTION:
  SMALL_PLAN_SERVICE_ACCESS:
  SMALL_PLAN_AZ:
  SMALL_PLAN_VM_TYPE:
  SMALL_PLAN_DISK_SIZE:
  SMALL_PLAN_TIMEOUT:
  SMALL_PLAN_TCP_KEEP_ALIVE:
  SMALL_PLAN_MAX_CLIENTS:
  SMALL_PLAN_LUA_SCRIPTING:
  SMALL_PLAN_INSTANCE_LIMIT:
  MEDIUM_PLAN_SELECTOR:
  MEDIUM_PLAN_NAME:
  MEDIUM_PLAN_DESCRIPTION:
  MEDIUM_PLAN_SERVICE_ACCESS:
  MEDIUM_PLAN_AZ:
  MEDIUM_PLAN_VM_TYPE:
  MEDIUM_PLAN_DISK_TYPE:
  MEDIUM_PLAN_TIMEOUT:
  MEDIUM_PLAN_TCP_KEEPALIVE:
  MEDIUM_PLAN_MAX_CLIENTS:
  MEDIUM_PLAN_LUA_SCRIPTING:
  MEDIUM_PLAN_INSTANCE_LIMIT:
  LARGE_PLAN_SELECTOR:
  LARGE_PLAN_NAME:
  LARGE_PLAN_DESCRIPTION:
  LARGE_PLAN_SERVICE_ACCESS:
  LARGE_PLAN_AZ:
  LARGE_PLAN_VM_TYPE:
  LARGE_PLAN_DISK_SIZE:
  LARGE_PLAN_TIMEOUT:
  LARGE_PLAN_KEEPALIVE:
  LARGE_PLAN_MAX_CLIENTS:
  LARGE_PLAN_LUA_SCRIPTING:
  LARGE_PLAN_INSTANCE_LIMIT:
  METRICS_POLLING_INTERVAL:
  BACKUP_SELECTOR:
  S3_ACCESS_KEY_ID:
  S3_SECRET_ACCESS_KEY:
  S3_ENDPOINT_URL:
  S3_REGION:
  S3_SIGNATURE_VERSION:
  S3_BUCKET_NAME:
  S3_PATH:
  S3_CRON_SCHEDULE:
  S3_BG_SAVE_TIMEOUT:
  SCP_SERVER:
  SCP_USERNAME:
  SCP_SSH_KEY:
  SCP_PATH:
  SCP_PORT:
  SCP_CRON_SCHEDULE:
  SCP_BG_SAVE_TIMEOUT:
  SCP_FINGERPRINT:
  AZURE_ACCOUNT:
  AZURE_STORAGE_ACCESS_KEY:
  AZURE_PATH:
  AZURE_CRON_SCHEDULE:
  AZURE_BG_SAVE_TIMEOUT:
  AZURE_CONTAINER:
  AZURE_BLOB_STORE_BASE_URL:
  GCS_PROJECT_ID:
  GCS_BUCKET_NAME:
  GCS_SERVICE_ACCOUNT_JSON:
  GCS_CRON_SCHEDULE:
  GCS_BG_SAVE_TIMEOUT:
  SYSLOG_SELECTOR:
  SYSLOG_ADDRESS:
  SYSLOG_PORT:
  SYSLOG_PROTOCOL:

run:
  path: pcf-pipelines/tasks/config-tiles/config-redis/task.sh
