---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

inputs:
  - name: pcf-pipelines
  - name: opsmgr-settings

params:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_PASSPHRASE:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_SETTINGS_FILENAME:
  OPSMAN_DISK_SIZE: 

run:
  path: pcf-pipelines/upgrade-ops-manager/gcp/tasks/resize-ops-manager-disk/task.sh
