---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: czero/cflinuxfs2
    
inputs:
  - name: pcf-pipelines
  - name: opsmgr-settings
  - name: cliaas-config
  
params:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  OPSMAN_GCP_CREDFILE_CONTENTS:
  OPSMAN_PROJECT: 
  OPSMAN_ZONE:
  OPSMAN_DISK_SIZE: 

run:
  path: pcf-pipelines/upgrade-ops-manager/gcp/tasks/resize-opsman-disk/task.sh
