platform: linux

image_resource:
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: curl

inputs:
- name: pivnet-product

outputs:
- name: notification-text

params:
  PRODUCT_FRIENDLY_NAME:
  FOUNDATION_NAME:

run:
  path: pcf-pipelines/tasks/create-slack-notification/task.sh
