---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

inputs:
  - name: pcf-pipelines
  - name: pivnet-product

params:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  PRODUCT_NAME:
  SINGLETON_JOB_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  SERVICES_NETWORK:
  RMQ_ADMIN_USERNAME:
  RMQ_ADMIN_PASSWORD:
  RMQ_PLUGINS:
  RMQ_SERVER_PORTS:
  RMQ_SSL_CERT:
  RMQ_PRIVATE_CERT:
  RMQ_CA_CERT:
  SSL_VERIFY:
  SSL_FAIL_IF_NO_PEER_CERT:
  SSL_VERIFICATION_DEPTH:
  ERLANG_COOKIE_NAME:
  RMQ_SERVER_CONFIG:
  RMQ_SECURITY_OPTION:
  RMQ_LOADBALANCER_DNS:
  METRICS_POLLING_INTERVAL:
  DISK_ALARM_THRESHOLD:
  RMQ_HAPROXY_INSTANCES:
  RMQ_SERVER_STATIC_IPS:
  IS_RMQ_POLICY_ENABLED:
  RMQ_POLICY_DEFINITION:
  RMQ_NW_PARTITION_HANDLING:
  SYSLOG_SELECTOR:
  SYSLOG_ADDRESS:
  SYSLOG_PORT:
  ENABLE_SINGLE_NODE_PLAN:
  SINGLE_NODE_PERSISTENT_DISK_TYPE:
  PLAN_NAME:
  PLAN_DESCRIPTION:
  PCF_MARKETPLACE_PRODUCT_IDENTIFIER:
  ON_DEMAND_BROKER_VM_TYPE:
  SERVICE_INSTANCE_COUNT:
  ON_DEMAND_BROKER_AZS:
  GLOBAL_SERVICE_INSTANCE_QUOTA:
  VM_EXTENSIONS:
  RMQ_SERVER_NODE_PERSISTENT_DISK_SIZE:

run:
  path: pcf-pipelines/tasks/config-tiles/config-rabbitmq/task.sh
