---
platform: linux

image_resource:
  type: docker-image
  source: {repository: czero/cflinuxfs2}

inputs:
  - name: pcf-pipelines
  - name: pivnet-product

params:
  OPSMAN_USERNAME:
  OPSMAN_PASSWORD:
  OPSMAN_DOMAIN_OR_IP_ADDRESS:
  PRODUCT_NAME:
  SINGLETON_JOB_AZ:
  OTHER_AZS:
  NETWORK_NAME:
  PLAN_NAME:
  PLAN_DESCRIPTION:
  PLAN_MAX_STORAGE_MB:
  PLAN_MAX_USER_CONNECTIONS:
  PLAN_PRIVATE:
  INNODB_STRICT_MODE:
  ALLOW_LOCAL_INFILE:
  ALLOW_CLI_HISTORY:
  DISABLE_REVERSE_DNS_LOOKUPS:
  ALLOW_REMOTE_ADMIN_ACCESS:
  READONLY_ADMIN_PASSWORD:
  MYSQL_START_TIMEOUT:
  CLUSTER_PROBE_TIMEOUT:
  ALLOW_TABLE_LOCKS:
  ENABLE_LARGE_INDICES:
  ENABLE_REPLICATION_DEBUG_LOGGING:
  SERVER_ACTIVITY_LOGGING:
  AUDIT_LOGGING_EVENTS:
  SERVER_AUDIT_EXCLUDED_USERS_CSV:
  TMP_TABLE_SIZE:
  TABLE_OPEN_CACHE:
  TABLE_DEFINITION_CACHE:
  BUFFER_POOL_SIZE:
  BUFFER_POOL_SIZE_PERCENT:
  BUFFER_POOL_SIZE_BYTES:
  MAX_CONNECTIONS:
  BINLOG_EXPIRE_DAYS:
  BACKUP_ENABLE:
  CRON_SCHEDULE:
  BACKUP_ALL_MASTERS:
  BACKUP_DESTINATION:
  S3_ENDPOINT:
  S3_BUCKET_NAME:
  S3_BUCKET_PATH:
  S3_ACCESS_KEY_ID:
  S3_SECRET_KEY:
  SCP_USER:
  SCP_SERVER:
  SCP_DESTINATION_DIR:
  SCP_PRIVATE_KEY:
  SCP_PORT:
  AZURE_STORAGE_ACCOUNT:
  AZURE_STORAGE_ACCESS_KEY:
  AZURE_CONTAINER:
  AZURE_CONTAINER_PATH:
  AZURE_BASE_URL:
  GCS_SERVICE_ACCOUNT_JSON:
  GCS_PROJECT_ID:
  GCS_BUCKET_NAME:
  OPTIONAL_PROTECTIONS:
  PREVENT_AUTO_JOIN:
  REPLICATION_CANARY:
  NOTIFY_ONLY:
  CANARY_POLL_FREQUENCY:
  CANARY_WRITE_READ_DELAY:
  RECIPIENT_EMAIL:
  QUOTA_ENFORCER_PAUSE:
  METRICS_POLLING_FREQUENCY:
  CLUSTER_NAME:
  SYSLOG_ENABLED:
  SYSLOG_ADDRESS:
  SYSLOG_PORT:
  MYSQL_SERVER_INSTANCE_TYPE:
  MYSQL_SERVER_INSTANCES:
  MYSQL_PERSISTENT_DISK_MB:
  BACKUP_PREPARE_INSTANCE_TYPE:
  BACKUP_PREPARE_INSTANCES:
  BACKUP_PREPARE_PERSISTENT_DISK_MB:
  MYSQL_PROXY_INSTANCE_TYPE:
  MYSQL_PROXY_INSTANCES:
  MONITORING_INSTANCE_TYPE:
  MONITORING_INSTANCES:
  MYSQL_BROKER_INSTANCE_TYPE:
  MYSQL_BROKER_INSTANCES:

run:
  path: pcf-pipelines/tasks/config-tiles/config-mysql/task.sh
